# Generated by Django 3.2 on 2021-08-04 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianpickupspot',
            name='pickup_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.pickupspot'),
        ),
    ]
