# Generated by Django 3.2 on 2021-06-11 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0003_auto_20210610_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardianslocation',
            name='source_of_location',
        ),
        migrations.AddField(
            model_name='guardianslocation',
            name='source_of_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
