# Generated by Django 3.2 on 2021-06-12 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0005_alter_guardianslocation_source_of_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardian',
            name='first_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='guardian',
            name='last_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
