# Generated by Django 3.2 on 2021-06-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20210612_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetails',
            name='geofencing_radius',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='guardianslocation',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='guardianslocation',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='guardianslocation',
            name='timeStamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schooldetails',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='schooldetails',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
    ]
