# Generated by Django 3.2 on 2021-07-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20210714_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickedupdroppedoff',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
