# Generated by Django 3.2 on 2021-06-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20210612_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldetails',
            name='geofencing_radius',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='schooldetails',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
        migrations.AlterField(
            model_name='schooldetails',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
    ]
