# Generated by Django 3.2 on 2021-07-15 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_pickedupdroppedoff_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickedupdroppedoff',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student'),
        ),
    ]
