# Generated by Django 3.2 on 2021-07-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_pickedupdroppedoff_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianslocation',
            name='distance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
