# Generated by Django 3.2 on 2021-06-20 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210612_1603'),
        ('school', '0008_auto_20210612_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearestParents',
            fields=[
                ('parents', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.schooluser')),
                ('distance', models.DecimalField(decimal_places=5, max_digits=15)),
            ],
        ),
    ]
