# Generated by Django 3.2 on 2021-08-03 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_pickedupdroppedoff_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_spot', models.CharField(max_length=128)),
                ('notes', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GuardianPickupSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.guardian')),
                ('pickup_spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.pickupspot')),
            ],
        ),
    ]
