# Generated by Django 3.2 on 2021-06-20 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_nearestparents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardianslocation',
            old_name='source_of_location',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='nearestparents',
            old_name='parents',
            new_name='user',
        ),
    ]
