# Generated by Django 3.2 on 2021-06-12 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_schooluser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooluser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='schooluser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='schooluser',
            name='last_name',
        ),
    ]
